# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlbumApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlbumApp

	pod 'IGListKit', '~> 4.0'
  	pod 'SnapKit', '~> 5.0.0'

  target 'AlbumAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlbumAppUITests' do
    # Pods for testing
  end

end
